Repository openenclave/openenclave, pull requests merged in 2018-11, with the labels that each got.

#983 convert props unittest to edger8r
  tests/props/args.h
  tests/props/enc/CMakeLists.txt
  tests/props/enc/enc.c
  tests/props/host/CMakeLists.txt
  tests/props/host/host.c
  tests/props/props.edl
Labels: testing

#1029 Remove failFast flag from Jenkins Pipeline.
  .jenkins/Jenkinsfile
Labels: testing

#1028 Enable build of oesign
  tools/CMakeLists.txt
Labels: devtools, windows

#1023 Test to verify TCS exhaustion to address missing thread binding coverage
  tests/thread/args.h
  tests/thread/host/host.cpp
  tests/thread/oethread_enc/enc.cpp
Labels: testing

#1051 Remove crypto_crls_cert_chains test certs
  tests/crypto_crls_cert_chains/data/IntermediateCA1.crt.pem
  tests/crypto_crls_cert_chains/data/IntermediateCA1.key.pem
  tests/crypto_crls_cert_chains/data/Leaf1.crt.pem
  tests/crypto_crls_cert_chains/data/Leaf1.key.pem
  tests/crypto_crls_cert_chains/data/Leaf2.crt.pem
  tests/crypto_crls_cert_chains/data/Leaf2.key.pem
  tests/crypto_crls_cert_chains/data/RootCA1.crt.pem
  tests/crypto_crls_cert_chains/data/RootCA1.key.pem
  tests/crypto_crls_cert_chains/data/intermediate_crl1.der
  tests/crypto_crls_cert_chains/data/intermediate_crl2.der
  tests/crypto_crls_cert_chains/data/root_crl1.der
  tests/crypto_crls_cert_chains/data/root_crl2.der
Labels: engineering, testing

#1052 Bugfix: Remove enclave's inclusion of system headers.
  cmake/compiler_settings.cmake
  cmake/get_c_compiler_dir.sh
  enclave/core/CMakeLists.txt
  enclave/core/dlmalloc/stddef.h
  libc/CMakeLists.txt
  libc/arc4random.c
  scripts/install-prereqs
  tests/VectorException/enc/CMakeLists.txt
  tests/VectorException/enc/init.cpp
  tests/VectorException/enc/sigill_handling.c
Labels: build, engineering

#1058 Updated changelog for QE Identity feature
  CHANGELOG.md
Labels: documentation

#1061 Moved 2 timing sensitive try_lock libcxx thread tests to unsupported
  tests/libcxx/tests.supported
  tests/libcxx/tests.unsupported
Labels: functionality, testing

#1060 Clean up OE_USE_LIBSGX
  enclave/CMakeLists.txt
  host/CMakeLists.txt
  tests/aesm/CMakeLists.txt
  tests/debug-mode/host/CMakeLists.txt
  tests/report/enc/CMakeLists.txt
Labels: build, engineering

#1084 Tests for oe-gdb.
  debugger/CMakeLists.txt
  debugger/oe-gdb
  debugger/ptraceLib/CMakeLists.txt
  debugger/pythonExtension/CMakeLists.txt
  tests/CMakeLists.txt
  tests/debugger/CMakeLists.txt
  tests/debugger/oe-gdb/CMakeLists.txt
  tests/debugger/oe-gdb/README.md
  tests/debugger/oe-gdb/commands.gdb
  tests/debugger/oe-gdb/enc/CMakeLists.txt
  tests/debugger/oe-gdb/enc/enc.c
  tests/debugger/oe-gdb/host/CMakeLists.txt
  tests/debugger/oe-gdb/host/host.c
  tests/debugger/oe-gdb/oe_gdb_test.edl
Labels: devtools, testing

#1049 Libc tests.broken scrub #768
  tests/libc/CMakeLists.txt
  tests/libc/enc/CMakeLists.txt
  tests/libc/tests.broken
  tests/libc/tests.supported
  tests/libc/tests.supported.gcc
Labels: testing

#1110 Removing include dir 'PROJECT_SOURCE_DIR/include' from CMakeList#958
  pkgconfig/CMakeLists.txt
Labels: bug

#1064 Added -Wconversion -Wpointer-arith flag #175 - enclave build
  common/asn1.h
  common/datetime.c
  common/quote.c
  common/report.c
  common/revocation.c
  common/sgxcertextensions.c
  common/tcbinfo.c
  enclave/CMakeLists.txt
  enclave/core/CMakeLists.txt
  enclave/core/backtrace.c
  enclave/core/calls.c
  enclave/core/debugmalloc.c
  enclave/core/exception.c
  enclave/core/hexdump.c
  enclave/core/hostcalls.c
  enclave/core/once.c
  enclave/core/sbrk.c
  enclave/core/snprintf.c
  enclave/core/string.c
  enclave/core/time.c
  enclave/crl.c
  enclave/ec.c
  enclave/random.c
  enclave/revocationinfo.c
  enclave/rsa.c
  include/openenclave/bits/safemath.h
  include/openenclave/internal/calls.h
  include/openenclave/internal/sgxtypes.h
  include/openenclave/internal/utils.h
Labels: engineering

#1071 Added -Wconversion -Wpointer-arith #175 - tests build (without source file changes)
  include/openenclave/internal/str.h
  tests/abortStatus/enc/CMakeLists.txt
  tests/abortStatus/host/CMakeLists.txt
  tests/aesm/CMakeLists.txt
  tests/cppException/enc/CMakeLists.txt
  tests/cppException/host/CMakeLists.txt
  tests/create-rapid/enc/CMakeLists.txt
  tests/create-rapid/host/CMakeLists.txt
  tests/crypto_crls_cert_chains/enc/CMakeLists.txt
  tests/crypto_crls_cert_chains/host/CMakeLists.txt
  tests/debug-mode/enc/CMakeLists.txt
  tests/debug-mode/host/CMakeLists.txt
  tests/echo/enc/CMakeLists.txt
  tests/echo/host/CMakeLists.txt
  tests/enclaveparam/enc/CMakeLists.txt
  tests/enclaveparam/host/CMakeLists.txt
  tests/file/enc/CMakeLists.txt
  tests/file/host/CMakeLists.txt
  tests/getenclave/enc/CMakeLists.txt
  tests/getenclave/host/CMakeLists.txt
  tests/hexdump/enc/CMakeLists.txt
  tests/hexdump/host/CMakeLists.txt
  tests/hostcalls/enc/CMakeLists.txt
  tests/hostcalls/host/CMakeLists.txt
  tests/initializers/enc/CMakeLists.txt
  tests/initializers/host/CMakeLists.txt
  tests/mbed/enc/CMakeLists.txt
  tests/mbed/host/CMakeLists.txt
  tests/mem/CMakeLists.txt
  tests/mixed_c_cpp/enc/CMakeLists.txt
  tests/mixed_c_cpp/host/CMakeLists.txt
  tests/ocall-create/enc/CMakeLists.txt
  tests/ocall-create/host/CMakeLists.txt
  tests/ocall/enc/CMakeLists.txt
  tests/ocall/host/CMakeLists.txt
  tests/oeedger8r/enc/CMakeLists.txt
  tests/oeedger8r/host/CMakeLists.txt
  tests/pingpong-shared/enc/CMakeLists.txt
  tests/pingpong-shared/host/CMakeLists.txt
  tests/pingpong/enc/CMakeLists.txt
  tests/pingpong/host/CMakeLists.txt
  tests/print/enc/CMakeLists.txt
  tests/print/host/CMakeLists.txt
  tests/props/enc/CMakeLists.txt
  tests/props/host/CMakeLists.txt
  tests/safecrt/enc/CMakeLists.txt
  tests/safecrt/host/CMakeLists.txt
  tests/stdcxx/enc/CMakeLists.txt
  tests/stdcxx/host/CMakeLists.txt
  tests/str/CMakeLists.txt
  tests/thread/host/CMakeLists.txt
  tests/thread/oethread_enc/CMakeLists.txt
  tests/thread/pthread_enc/CMakeLists.txt
  tests/threadcxx/enc/CMakeLists.txt
  tests/threadcxx/host/CMakeLists.txt
Labels: engineering

#1065 Addded -Wconversion -Wpointer-arith flags #175 - Host build
  host/CMakeLists.txt
  host/calls.c
  host/create.c
  host/crypto/openssl/asn1.c
  host/crypto/openssl/cert.c
  host/crypto/openssl/crl.c
  host/crypto/openssl/ec.c
  host/crypto/openssl/key.c
  host/crypto/openssl/random.c
  host/crypto/openssl/rsa.c
  host/elf.c
  host/files.c
  host/linux/aesm.c
  host/linux/exception.c
  host/linux/time.c
  host/linux/windows.c
  host/loadpe.c
  host/ocalls.c
  host/sgxload.c
  host/sgxsign.c
  host/strings.c
  include/openenclave/bits/types.h
  include/openenclave/host.h
  include/openenclave/internal/str.h
Labels: engineering
