Repository openenclave/openenclave, pull requests merged in 2018-10, with the labels that each got.

#886 Remove merge=union attributes
  .gitattributes
Labels: engineering

#885 File-encryptor sample: fixed PKCS5 paddings for block aligned contents
  samples/file-encryptor/host/Makefile
  samples/file-encryptor/host/host.cpp
Labels: documentation

#888 Make oe_random be public in enclave.h
  enclave/random.c
  host/crypto/random.c
  include/openenclave/enclave.h
  include/openenclave/internal/random.h
  tests/crypto/enclave/enc/enc.c
  tests/crypto/random_tests.c
Labels: functionality

#825 Simplify _find_enclave_properties_header in host/create.c #806
  host/create.c
Labels: engineering

#903 Refactored prereqs makefiles to use apt repos.
  docs/GettingStartedDocs/SGX1FLCGettingStarted.md
  prereqs/az-dcap-client/Makefile
  prereqs/dcap/Makefile
Labels: engineering

#926 Disable Kabylake builds in CI until further notice.
  .jenkins/Jenkinsfile
Labels: testing

#889 Fix #823: libcxx test failures with RelWithDebInfo and clang
  tests/libcxx/CMakeLists.txt
  tests/libcxx/enc/CMakeLists.txt
  tests/libcxx/tests.broken
  tests/libcxx/tests.supported
Labels: engineering, testing

#929 Upgrading mbdetls library to 2.7.6
  3rdparty/mbedtls/mbedtls/ChangeLog
  3rdparty/mbedtls/mbedtls/doxygen/input/doc_mainpage.h
  3rdparty/mbedtls/mbedtls/doxygen/mbedtls.doxyfile
  3rdparty/mbedtls/mbedtls/include/mbedtls/version.h
  3rdparty/mbedtls/mbedtls/library/CMakeLists.txt
  3rdparty/mbedtls/mbedtls/library/ccm.c
  3rdparty/mbedtls/mbedtls/library/ecp.c
  3rdparty/mbedtls/mbedtls/library/ssl_ciphersuites.c
  3rdparty/mbedtls/mbedtls/library/ssl_cli.c
  3rdparty/mbedtls/mbedtls/library/ssl_srv.c
  3rdparty/mbedtls/mbedtls/library/ssl_tls.c
  3rdparty/mbedtls/mbedtls/library/x509_crt.c
  3rdparty/mbedtls/mbedtls/programs/pkey/pk_decrypt.c
  3rdparty/mbedtls/mbedtls/programs/pkey/pk_encrypt.c
  3rdparty/mbedtls/mbedtls/programs/ssl/ssl_mail_client.c
  3rdparty/mbedtls/mbedtls/programs/x509/cert_write.c
  3rdparty/mbedtls/mbedtls/tests/ssl-opt.sh
  3rdparty/mbedtls/mbedtls/tests/suites/test_suite_pkparse.data
  3rdparty/mbedtls/mbedtls/tests/suites/test_suite_version.data
  3rdparty/mbedtls/update.make
  CHANGELOG.md
Labels: functionality, security

#933 Added package upstreaming documentation.
  docs/CICD/PackageUpstreaming.md
Labels: documentation

#947 fixing typos in samples
  samples/data-sealing/README.md
  samples/data-sealing/enc2/ecalls.cpp
  samples/local_attestation/README.md
Labels: testing

#949 Removed 2 of the try_to_lock tests as they are timing sensitive
  tests/libcxxthrd/tests.supported.default
Labels: testing

#957 Install oeedger8r specific headers in SDK
  include/CMakeLists.txt
Labels: functionality

#960 Fix tests/libcxx test exclusion
  tests/libcxx/CMakeLists.txt
  tests/libcxx/enc/CMakeLists.txt
Labels: bug, testing

#970 Fix build error under cmake .. -DUSE_LIBSGX=1 -DOE_TRACE_LEVEL=2
  tests/ecall_ocall/host/host.cpp
Labels: bug

#966 Fix issue with building oeedger8r on windows
  tools/oeedger8r/CMakeLists.txt
Labels: engineering

#976 Improvements to edger8r
  tests/memory/enc/basic.c
  tests/oeedger8r/edl/basic.edl
  tests/oeedger8r/enc/testbasic.cpp
  tests/oeedger8r/host/testbasic.cpp
  tools/oeedger8r/Emitter.ml
Labels: bug

#987 Removed CICD docs.
  docs/CICD/PackageUpstreaming.md
Labels: documentation

#984 Fix check for 64-bit build
  cmake/compiler_settings.cmake
Labels: engineering

#993 Enabled Windows CI builds.
  .jenkins/Jenkinsfile
Labels: testing, windows

#995 Enable more logging for libcxx thread tests before oe_abort
  tests/libcxx/enc/enc.cpp
  tests/libcxx/host/host.cpp
Labels: bug, testing

#980 Libcxx broken tests scrub #151
  tests/libcxx/CMakeLists.txt
  tests/libcxx/enc/CMakeLists.txt
  tests/libcxx/tests.broken
  tests/libcxx/tests.supported
  tests/libcxx/tests.unsupported
Labels: testing

#1005 Added oeedger8r uploads to nightly build.
  .jenkins/Packaging.Jenkinsfile
Labels: engineering

#1006 Moved test libcxxtest-std_thread_futures_futures.unique_future_get.pass to broken
  tests/libcxx/tests.broken
  tests/libcxx/tests.supported
  tests/libcxx/tests.supported.default
Labels: bug, testing

#932 Wnd memory management in simulated enclaves
  host/sgxload.c
Labels: bug, functionality

#1012 Move pre-commit requirements stage into parallel build
  .jenkins/Jenkinsfile
Labels: engineering
