Repository openenclave/openenclave, pull requests merged in 2018-12, with the labels that each got.

#1167 Document the required CMake version
  docs/GettingStartedDocs/AdvancedBuildInfo.md
  docs/GettingStartedDocs/GettingStarted.Windows.md
Labels: documentation

#1142 Enabled unsupported test for g++ alone #830
  tests/libcxx/CMakeLists.txt
  tests/libcxx/enc/CMakeLists.txt
  tests/libcxx/tests.supported
  tests/libcxx/tests.unsupported
Labels: testing

#1177 Switch to using C++14 as our default (internal) standard
  3rdparty/libcxx/CMakeLists.txt
  cmake/compiler_settings.cmake
  libc/CMakeLists.txt
  tests/abortStatus/host/CMakeLists.txt
  tests/create-rapid/host/CMakeLists.txt
  tests/crypto_crls_cert_chains/enc/CMakeLists.txt
  tests/crypto_crls_cert_chains/host/CMakeLists.txt
  tests/ecall_ocall/host/CMakeLists.txt
  tests/libcxx/enc/CMakeLists.txt
  tests/libcxx/host/CMakeLists.txt
  tests/libcxxrt/enc/CMakeLists.txt
  tests/memory/host/CMakeLists.txt
  tests/oeedger8r/enc/CMakeLists.txt
  tests/oeedger8r/host/CMakeLists.txt
  tests/qeidentity/enc/CMakeLists.txt
  tests/report/enc/CMakeLists.txt
  tests/sealKey/host/CMakeLists.txt
  tests/stdcxx/enc/CMakeLists.txt
  tests/thread/host/CMakeLists.txt
  tests/threadcxx/enc/CMakeLists.txt
  tests/threadcxx/host/CMakeLists.txt
Labels: build

#1179 Update changelog with updated CMake/C++ versions
  CHANGELOG.md
Labels: documentation

#972 Making single implementation for random functionality at common/rand.c,for both oecore and oelibcoelibc.
  common/common.h
  common/rand.S
  common/rand.asm
  enclave/core/CMakeLists.txt
  enclave/core/entropy.c
  libc/CMakeLists.txt
  libc/arc4random.c
  tests/crypto/enclave/enc/CMakeLists.txt
  tests/crypto/host/CMakeLists.txt
  tests/crypto/rdrand_test.c
  tests/crypto/tests.c
  tests/crypto/tests.h
Labels: engineering

#1201 Re-enabled Non-sim Container CI Tests.
  .jenkins/Jenkinsfile
Labels: ci/cd

#1233 Hotfix port of QE version dependency from master.
  common/quote.c
Labels: bug

#1245 Updated CHANGELOG.md for v0.4.1.
  CHANGELOG.md
Labels: documentation

#1248 Added Ubuntu 18.04 to CI and refactored Jenkinsfile.
  .jenkins/Jenkinsfile
Labels: ci/cd

#1265 Replace wrap_tests.sh with CMake code
  tests/libc/enc/CMakeLists.txt
  tests/libc/enc/include.c.in
  tests/libc/enc/tests.c.in
  tests/libc/enc/wrap_tests.sh
Labels: build

#1268 Build all supported tests on Windows using clang cross-compilation
  3rdparty/libunwind/CMakeLists.txt
  3rdparty/musl/patches/endian.h
  cmake/add_enclave.cmake
  cmake/add_enclave_test.cmake
  cmake/maybe_build_using_clangw.cmake
  tests/CMakeLists.txt
  tests/SampleApp/CMakeLists.txt
  tests/SampleAppCRT/CMakeLists.txt
  tests/VectorException/CMakeLists.txt
  tests/abortStatus/CMakeLists.txt
  tests/backtrace/CMakeLists.txt
  tests/bigmalloc/CMakeLists.txt
  tests/cppException/CMakeLists.txt
  tests/create-errors/CMakeLists.txt
  tests/create-rapid/CMakeLists.txt
  tests/crypto_crls_cert_chains/CMakeLists.txt
  tests/debug-mode/CMakeLists.txt
  tests/ecall/CMakeLists.txt
  tests/ecall_ocall/CMakeLists.txt
  tests/echo/CMakeLists.txt
  tests/enclaveparam/CMakeLists.txt
  tests/file/CMakeLists.txt
  tests/getenclave/CMakeLists.txt
  tests/hexdump/CMakeLists.txt
  tests/hostcalls/CMakeLists.txt
  tests/initializers/CMakeLists.txt
  tests/libc/CMakeLists.txt
  tests/libcxx/CMakeLists.txt
  tests/libcxxrt/CMakeLists.txt
  tests/libunwind/CMakeLists.txt
  tests/mbed/CMakeLists.txt
  tests/memory/CMakeLists.txt
  tests/mixed_c_cpp/CMakeLists.txt
  tests/ocall-create/CMakeLists.txt
  tests/ocall/CMakeLists.txt
  tests/oeedger8r/CMakeLists.txt
  tests/oeedger8r/enc/CMakeLists.txt
  tests/pingpong-shared/CMakeLists.txt
  tests/pingpong/CMakeLists.txt
  tests/print/CMakeLists.txt
  tests/props/CMakeLists.txt
  tests/qeidentity/CMakeLists.txt
  tests/report/CMakeLists.txt
  tests/safecrt/CMakeLists.txt
  tests/sealKey/CMakeLists.txt
  tests/stdc/CMakeLists.txt
  tests/stdcxx/CMakeLists.txt
  tests/thread/CMakeLists.txt
  tests/thread_local/CMakeLists.txt
  tests/thread_local/host/host.cpp
  tests/threadcxx/CMakeLists.txt
Labels: build, ci/cd, devtools, windows
