Repository openenclave/openenclave, pull requests merged in 2019-11, with the labels that each got.

#2295 Update project to use DCO instead of CLA
  CMakeLists.txt
  README.md
  docs/Contributing.md
  scripts/README.md
  scripts/commit-msg
Labels: documentation, engineering

#2300 Publish location of CGC minutes
  docs/Committers.md
Labels: documentation

#2293 Add support for V2 of SGX Collaterals/Endorsements.
  docs/DesignDocs/SGX_Endorsements_V2.md
Labels: SGX, design

#2312 Fix code formatting in Windows Getting Started doc
  docs/GettingStartedDocs/Contributors/WindowsSGX1FLCGettingStarted.md
Labels: documentation

#2309 Remove esy on-the-fly installation from CI containers
  .jenkins/Jenkinsfile
Labels: ci/cd

#2305 Update dependency graph
  docs/GettingStartedDocs/Contributors/AdvancedBuildInfo.md
  docs/GettingStartedDocs/DependencyGraph.svg
Labels: documentation

#2262 Attestation Plugin Design Doc
  docs/DesignDocs/CustomAttestation.md
Labels: design

#2253 Design review: Remote attestation collaterals API.
  docs/DesignDocs/RemoteAttestationCollaterals.md
Labels: design

#2324 Optimization/Security: Reduce TCB via gc-sections.
  enclave/core/CMakeLists.txt
  host/sgx/asmdefs.h
  host/sgx/calls.c
  pkgconfig/CMakeLists.txt
  tests/debugger/oegdb/enc/enc.c
Labels: SGX, core, linux, security, windows

#2321 Make sure the latest versions of dependencies is present
  scripts/ansible/roles/linux/az-dcap-client/tasks/stable-install.yml
  scripts/ansible/roles/linux/common/tasks/apt-repo.yml
  scripts/ansible/roles/linux/docker/tasks/ci-setup.yml
  scripts/ansible/roles/linux/docker/tasks/stable-install.yml
  scripts/ansible/roles/linux/intel/tasks/sgx-driver.yml
  scripts/ansible/roles/linux/intel/tasks/sgx-packages.yml
  scripts/ansible/roles/linux/jenkins/tasks/slave-setup.yml
  scripts/ansible/roles/linux/openenclave/tasks/environment-setup-cross-arm.yml
  scripts/ansible/roles/linux/openenclave/tasks/environment-setup.yml
  scripts/ansible/roles/linux/openenclave/tasks/stable-install.yml
Labels: ci/cd

#2319 Adopt Contributors Covenant v1.4 Code of Conduct
  README.md
  docs/CodeOfConduct.md
  docs/Committers.md
  docs/Contributing.md
  docs/Governance.md
  samples/file-encryptor/testfile
Labels: documentation

#2337 Remove debug.h support statement from MbedtlsSupport.md
  docs/MbedtlsSupport.md
Labels: documentation

#2176 Proposal: Enforcing full EDL serialization
  docs/DesignDocs/full_edl_serialization.md
Labels: design

#2338 Remove workaround in dune build of Intel sources
  tools/oeedger8r/README.md
  tools/oeedger8r/intel/dune
  tools/oeedger8r/src/Emitter.ml
  tools/oeedger8r/src/main.ml
Labels: devtools

#2341 Fix broken link
  docs/Contributing.md
Labels: documentation

#2149 Fix polymorphic exceptions caught by value
  tests/cppException/enc/cppException.cpp
  tests/stdcxx/enc/enc.cpp
Labels: testing
