Repository openenclave/openenclave, pull requests merged in 2019-03, with the labels that each got.

#1517 Fixed test to account for leap year days.
  tests/crypto/crl_tests.c
Labels: blocker

#1512 Fix regression: Wait until release becomes 1.
  tests/ecall_ocall/enc/enc.cpp
Labels: bug, testing

#1513 Exclude OE_API_VERSION=2 from CMake package
  enclave/core/CMakeLists.txt
  host/CMakeLists.txt
Labels: build

#1324 Add Ubuntu 18.04 support to libcxx_tests.Jenkinsfile
  .jenkins/libcxx_tests.Jenkinsfile
  .jenkins/provision/templates/oe-engine/ubuntu-bionic.json
Labels: ubuntu-18.04

#1554 Use GCC 7 on Ubuntu 18.04
  scripts/ansible/roles/linux/openenclave/tasks/environment-setup.yml
Labels: ci/cd

#1566 [Ansible] Use role vars instead of global group vars
  scripts/ansible/inventory/group_vars/linux-agents
  scripts/ansible/roles/linux/intel/tasks/sgx-driver.yml
  scripts/ansible/roles/linux/intel/vars/bionic.yml
  scripts/ansible/roles/linux/intel/vars/xenial.yml
Labels: ci/cd

#1545 Update libc & libcxx support docs
  docs/LibcSupport.md
  docs/LibcxxSupport.md
Labels: documentation

#1597 Incremented g_qeisvsvn from 1 to 2.
  CHANGELOG.md
  common/sgx/qeidentity.c
Labels: security

#1611 Added licenses directory to package.
  CMakeLists.txt
Labels: bug, build, documentation

#1629 Remove __oe_assert_fail from doxygen docs, fix for #1626
  include/openenclave/enclave.h
Labels: bug, documentation

#1585 Update CMake readme for changed dependencies
  cmake/sdk_cmake_targets_readme.md
Labels: build

#1616 Fix formatting in CHANGELOG
  CHANGELOG.md
Labels: documentation

#1630 Update buildandsign.md to include a link to CMake documentation
  docs/GettingStartedDocs/buildandsign.md
Labels: documentation

#1628 Moved contributor documents to contributors folder.
  docs/GettingStartedDocs/Contributors/AdvancedBuildInfo.md
  docs/GettingStartedDocs/Contributors/AdvancedTestInfo.md
  docs/GettingStartedDocs/Contributors/AnsibleGettingStarted.md
  docs/GettingStartedDocs/Contributors/InstallInfo.md
  docs/GettingStartedDocs/Contributors/SGX1FLCGettingStarted.md
  docs/GettingStartedDocs/Contributors/SGX1GettingStarted.md
  docs/GettingStartedDocs/Contributors/SimulatorGettingStarted.md
  docs/GettingStartedDocs/GettingStarted.md
Labels: documentation

#1640 Added 18.04 Install OE SDK document and updated 16.04.
  README.md
  docs/GettingStartedDocs/install_oe_sdk-Ubuntu_16.04.md
  docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md
  docs/GettingStartedDocs/install_oe_sdk.md
Labels: documentation

#1644 Document support for thread-local storage within enclaves.
  docs/ThreadLocalSupport.md
Labels: documentation

#1646 Fixes to AdvancedBuildInfo.md
  docs/GettingStartedDocs/Contributors/AdvancedBuildInfo.md
Labels: documentation, engineering

#1636 Add auto-signing to the samples
  samples/data-sealing/CMakeLists.txt
  samples/data-sealing/common/CMakeLists.txt
  samples/data-sealing/host/CMakeLists.txt
  samples/file-encryptor/CMakeLists.txt
  samples/file-encryptor/enc/CMakeLists.txt
  samples/file-encryptor/host/CMakeLists.txt
  samples/helloworld/CMakeLists.txt
  samples/helloworld/enc/CMakeLists.txt
  samples/helloworld/host/CMakeLists.txt
  samples/local_attestation/common/CMakeLists.txt
  samples/local_attestation/enc1/CMakeLists.txt
  samples/local_attestation/enc2/CMakeLists.txt
  samples/local_attestation/host/CMakeLists.txt
  samples/remote_attestation/common/CMakeLists.txt
  samples/remote_attestation/enc1/CMakeLists.txt
  samples/remote_attestation/enc2/CMakeLists.txt
  samples/remote_attestation/host/CMakeLists.txt
Labels: build, documentation, samples

#1648 Fix dependency graph link
  docs/GettingStartedDocs/Contributors/AdvancedBuildInfo.md
Labels: documentation
