Repository openenclave/openenclave, pull requests merged in 2019-10, with the labels that each got.

#2226 Fix incremental rebuild due to `add_custom_target`
  tests/crypto/data/CMakeLists.txt
  tests/crypto_crls_cert_chains/data/CMakeLists.txt
Labels: build

#2234 Install nuget.exe to Program Files for building NuGet packages.
  scripts/install-windows-prereqs.ps1
Labels: windows

#2239 Update CHANGELOG.md for v0.7.0-rc1
  CHANGELOG.md
Labels: documentation

#2223 Preserve Windows & Linux ABI expectations on ECALL
  enclave/core/sgx/enter.S
  host/CMakeLists.txt
  host/sgx/windows/enter.asm
  host/sgx/windows/host_context.asm
  include/openenclave/internal/constants_x64.h
Labels: core, windows

#2248 Update CMakeSettings.json with NUGET_PACKAGE_PATH
  CMakeSettings.json
Labels: build, windows

#2238 Add nuget and hostverify package builds to Packaging.Jenkinsfile.
  .jenkins/Packaging.Jenkinsfile
Labels: ci/cd

#2254 Remove lockless queue implementation
  common/lockless_queue.c
  enclave/CMakeLists.txt
  host/CMakeLists.txt
  include/openenclave/internal/lockless_queue.h
  tests/CMakeLists.txt
  tests/lockless_queue/CMakeLists.txt
  tests/lockless_queue/enc/CMakeLists.txt
  tests/lockless_queue/enc/enc.c
  tests/lockless_queue/host/CMakeLists.txt
  tests/lockless_queue/host/host.c
  tests/lockless_queue/lockless_queue.edl
Labels: engineering

#2229 Add a release manager selection process to Releasing.md
  docs/Releasing.md
Labels: process

#2230 Set John Kordich as the Release Manager.
  docs/Committers.md
Labels: process

#2250 Unify the installation/build/runtime flows for SGX and SGXFLC
  .jenkins/Jenkinsfile
  .jenkins/custom_label.Jenkinsfile
  .jenkins/libcxx_tests.Jenkinsfile
  CHANGELOG.md
  CMakeLists.txt
  CMakeSettings.json
  cmake/openenclave-config.cmake.in
  docs/GettingStartedDocs/Contributors/SGX1GettingStarted.md
  docs/GettingStartedDocs/Contributors/SimulatorGettingStarted.md
  docs/GettingStartedDocs/Contributors/WindowsInstallInfo.md
  docs/GettingStartedDocs/Contributors/WindowsManualSGX1Prereqs.md
  docs/GettingStartedDocs/Contributors/WindowsSGX1FLCGettingStarted.md
  docs/GettingStartedDocs/Contributors/building_oe_sdk.md
  enclave/core/CMakeLists.txt
  host/CMakeLists.txt
  host/sgx/linux/aesm.c
  host/sgx/ocalls.c
  host/sgx/quote.c
  host/sgx/report.c
  host/sgx/sgxload.c
  host/sgx/sgxquote.c
  host/sgx/sgxsign.c
  host/sgx/windows/aesm.c
  include/openenclave/internal/aesm.h
  pkgconfig/CMakeLists.txt
  samples/CMakeLists.txt
  samples/test-samples.cmake
  scripts/install-windows-prereqs.ps1
  scripts/test-build-config
  tests/CMakeLists.txt
  tests/aesm/CMakeLists.txt
  tests/aesm/main.cpp
  tests/attestation_cert_apis/host/host.cpp
  tests/bigmalloc/host/host.c
  tests/debug-mode/host/host.c
  tests/qeidentity/enc/CMakeLists.txt
  tests/qeidentity/enc/enc.cpp
  tests/qeidentity/host/CMakeLists.txt
  tests/qeidentity/host/host.cpp
  tests/qeidentity/host/qeidentifyinfo.cpp
  tests/report/common/tests.cpp
  tests/report/enc/enc.cpp
  tests/report/host/CMakeLists.txt
  tests/report/host/host.cpp
  tests/report/host/tcbinfo.cpp
  tests/tls_e2e/client_enc/CMakeLists.txt
  tests/tls_e2e/host/host.cpp
  tests/tls_e2e/server_enc/CMakeLists.txt
  tests/tools/oecert/host/host.cpp
Labels: SGX, ansible, build, ci/cd, core, devtools, documentation, engineering, samples, ubuntu-18.04, windows

#2265 Fix errors in Windows documentations
  docs/GettingStartedDocs/Contributors/WindowsInstallInfo.md
  docs/GettingStartedDocs/Contributors/WindowsManualInstallPrereqs.md
  docs/GettingStartedDocs/Contributors/WindowsManualSGX1Prereqs.md
  docs/GettingStartedDocs/Contributors/WindowsSGX1FLCGettingStarted.md
  docs/GettingStartedDocs/Contributors/WindowsSGX1GettingStarted.md
  docs/GettingStartedDocs/Contributors/building_oe_sdk.md
  docs/GettingStartedDocs/Windows_using_oe_sdk.md
Labels: documentation, windows
