Repository openenclave/openenclave, pull requests merged in 2019-02, with the labels that each got.

#1404 Removal of OE_ENCLAVE_TYPE_UNKNOWN
  CHANGELOG.md
  include/openenclave/bits/types.h
  tests/create-errors/host/host.c
Labels: core, trustzone

#1406 Fixes for Windows CI Powershell script for Release configurations
  scripts/test-build-config.ps1
Labels: bug, ci/cd

#1413 Skip assertion in case of no .tdata
  host/sgx/loadelf.c
  tests/CMakeLists.txt
  tests/thread_local/CMakeLists.txt
  tests/thread_local/thread_local.edl
  tests/thread_local_no_tdata/CMakeLists.txt
  tests/thread_local_no_tdata/enc/CMakeLists.txt
  tests/thread_local_no_tdata/enc/enc.cpp
  tests/thread_local_no_tdata/host/#host.cpp#
  tests/thread_local_no_tdata/host/CMakeLists.txt
  tests/thread_local_no_tdata/host/host.cpp
  tests/thread_local_no_tdata/no_tdata.edl
  tests/thread_locals/CMakeLists.txt
  tests/thread_locals/README.md
Labels: core

#1411 Disallow bors r+ on PRs with the label "do not merge"
  bors.toml
Labels: ci/cd

#1418 Switched to Jenkins agent pre-provisioning role
  scripts/ansible/jenkins-setup.yml
  scripts/ansible/roles/common/jenkins-agent/tasks/agent-provision.yml
  scripts/ansible/roles/linux/jenkins/tasks/slave-setup.yml
  scripts/ansible/roles/windows/jenkins/tasks/slave-setup.yml
Labels: blocked

#1462 Remove custom oelibc pthread member from td_t
  enclave/core/sgx/errno.c
  enclave/core/sgx/linux/threadlocal.c
  include/openenclave/internal/sgxtypes.h
  libc/pthread.c
Labels: core

#1468 Remove libunwind Gtrace.c workaround
  3rdparty/libunwind/CMakeLists.txt
  3rdparty/libunwind/Gtrace.c
Labels: core

#1504 Increase CI testing stages timeouts
  .jenkins/Jenkinsfile
Labels: ci/cd
