Repository openenclave/openenclave, pull requests merged in 2019-07, with the labels that each got.

#2012 Jenkins: Reduce the number of stages per CI run
  .jenkins/Jenkinsfile
Labels: ci/cd

#2034 Update GettingStartedDocs and CHANGELOG.md
  CHANGELOG.md
  docs/GettingStartedDocs/install_oe_sdk-Ubuntu_16.04.md
  docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md
Labels: documentation

#2035 Fixes: Add size field. Initialize debug_enclave member.
  debugger/pythonExtension/gdb_sgx_plugin.py
  host/sgx/create.c
  include/openenclave/internal/debugrt/host.h
  tests/debugger/oegdb/commands.gdb
  tests/debugger/oegdb/host/contract.c
Labels: devtools

#2052 Remove strcmp weak alias (one-line change)
  enclave/core/string.c
Labels: engineering

#2067 Update Visual Studio builds to support DCAP libraries
  CMakeSettings.json
  host/sgx/windows/sgxquoteproviderloader.c
  scripts/clangw
Labels: build, windows

#2063 Converge crypto implementations
  common/cert.c
  enclave/crypto/cert.c
  host/crypto/bcrypt/rsa.c
  host/crypto/magic.h
  host/crypto/openssl/cert.c
  host/crypto/openssl/crl.c
  host/crypto/openssl/ec.c
  host/crypto/openssl/rsa.c
  include/openenclave/internal/crypto/cert.h
Labels: engineering

#2064 Enable tests/crypto/host random tests on Windows
  common/sgx/rand.asm
  tests/crypto/data/CMakeLists.txt
  tests/crypto/host/CMakeLists.txt
  tests/crypto/random_tests.c
  tests/crypto/tests.c
Labels: testing

#2065 Clean up oe_memalign semantics in enclave.
  common/oe_host_stdlib.h
  enclave/core/malloc.c
  include/openenclave/corelibc/stdlib.h
  tests/crypto/ec_tests.c
Labels: core, testing
