Repository openenclave/openenclave, pull requests merged in 2019-09, with the labels that each got.

#2121 Add Jenkins package tests
  .jenkins/Dockerfile.full
  .jenkins/Jenkinsfile
Labels: build, ci/cd

#2122 Modified install-windows-prereq.ps1 input parameters.
  docs/GettingStartedDocs/GettingStarted.Windows.md
  scripts/ansible/oe-windows-acc-setup.yml
  scripts/install-windows-prereqs.ps1
Labels: build, ci/cd

#2142 Improve pre-commit hook
  scripts/pre-commit
Labels: devtools

#2156 Update maintainers list
  docs/Maintainers.md
Labels: documentation

#2173 Setup CODEOWNERS
  docs/CODEOWNERS
  scripts/.check-license.ignore
Labels: devtools

#2125 The 2nd half installment of switchless ocalls
  common/result.c
  enclave/core/CMakeLists.txt
  enclave/core/arena.c
  enclave/core/arena.h
  enclave/core/hostcalls.c
  enclave/core/optee/gp.c
  enclave/core/optee/hostcalls.c
  enclave/core/sgx/calls.c
  enclave/core/sgx/hostcalls.c
  enclave/core/shm.c
  enclave/core/shm.h
  enclave/core/switchlesscalls.c
  enclave/core/switchlesscalls.h
  host/CMakeLists.txt
  host/calls.h
  host/hostthread.h
  host/linux/hostthread.c
  host/optee/linux/enclave.c
  host/sgx/calls.c
  host/sgx/create.c
  host/sgx/enclave.h
  host/sgx/switchless.c
  host/traceh.c
  host/windows/hostthread.c
  include/openenclave/bits/result.h
  include/openenclave/host.h
  include/openenclave/internal/atomic.h
  include/openenclave/internal/calls.h
  include/openenclave/internal/switchless.h
  include/openenclave/internal/thread.h
  include/openenclave/internal/utils.h
  tests/create-errors/host/host.c
  tests/switchless/enc/CMakeLists.txt
  tests/switchless/enc/enc.c
  tests/switchless/host/CMakeLists.txt
  tests/switchless/host/host.c
  tests/switchless/switchless.edl
  tools/oeedger8r/Emitter.ml
Labels: core, functionality

#2186 Rename Maintainers.md and GovernanceModel.md
  README.md
  docs/CODEOWNERS
  docs/Committers.md
  docs/Contributing.md
  docs/Governance.md
  docs/Releasing.md
Labels: documentation

#2190 Fix some language in contributing and governance
  docs/Contributing.md
  docs/Governance.md
Labels: documentation

#2183 Clean copied sources and binaries from ExternalProject_Add rules
  3rdparty/CMakeLists.txt
  3rdparty/libcxx/CMakeLists.txt
  3rdparty/libcxx/libcxx/benchmarks/CMakeLists.txt
  3rdparty/libcxx/libcxx/utils/google-benchmark/cmake/HandleGTest.cmake
  3rdparty/musl/CMakeLists.txt
Labels: build

#2069 OpenSSL standalone install on Windows
  scripts/install-windows-prereqs.ps1
Labels: testing, windows

#2185 Fix file-encryptor README
  samples/file-encryptor/README.md
Labels: documentation

#2165 Add proposed quorum rules
  docs/Committers.md
Labels: process
