Repository openenclave/openenclave, pull requests merged in 2019-06, with the labels that each got.

#1848 Added dual docker registry push, private/public
  .jenkins/build_docker_images.Jenkinsfile
Labels: ansible

#1846 Add SDK version to OE Environment preparation
  scripts/ansible/roles/windows/openenclave/tasks/environment-setup.yml
Labels: ci/cd

#1853 Minimum changes needed to refactor against `edger8r_params`
  tools/oeedger8r/Emitter.ml
Labels: devtools

#1855 Excluded attestion_cert_api test from running on environment where OE_USE_LIBSGX is undefined
  tests/attestation_cert_apis/host/host.cpp
Labels: bug

#1815 Make pkgconfig relocatable
  pkgconfig/CMakeLists.txt
  pkgconfig/oeenclave-clang++.pc
  pkgconfig/oeenclave-clang.pc
  pkgconfig/oeenclave-g++.pc
  pkgconfig/oeenclave-gcc.pc
  pkgconfig/oehost-clang++.pc
  pkgconfig/oehost-clang.pc
  pkgconfig/oehost-g++.pc
  pkgconfig/oehost-gcc.pc
  samples/test-samples.cmake
Labels: build

#1859 OCall logging bugfixes
  host/sgx/calls.c
Labels: engineering

#1863 Refactor use of `get_deepcopy`
  tools/oeedger8r/Emitter.ml
Labels: devtools

#1869 Fix extraneous uses of `sprintf` in edger8r
  tools/oeedger8r/Emitter.ml
Labels: devtools

#1867 Switch to GLOBAL_TIMEOUT
  .jenkins/Jenkinsfile
  .jenkins/Nightly_packages_testing.Jenkinsfile
  .jenkins/Packaging.Jenkinsfile
  .jenkins/build_docker_images.Jenkinsfile
  .jenkins/build_vhd.Jenkinsfile
  .jenkins/libcxx_tests.Jenkinsfile
  src/jenkins/common/Openenclave.groovy
Labels: ci/cd

#1879 Fix Jenkins CI shared lib regression
  src/jenkins/common/Openenclave.groovy
Labels: ci/cd

#1875 Isolate all I/O side effects into one location
  tools/oeedger8r/Emitter.ml
Labels: devtools

#1900 Disable Intel's edger8r from looking for GCC
  tools/oeedger8r/intel/Preprocessor.ml
Labels: bug, devtools

#1907 Remove the Common Jenkins Library
  src/jenkins/common/Openenclave.groovy
Labels: ci/cd

#1897 Timeout: ctest --timeout 480
  .jenkins/Jenkinsfile
  .jenkins/Packaging.Jenkinsfile
  .jenkins/libcxx_tests.Jenkinsfile
Labels: ci/cd

#1878 Make openssl available to the command line with ansible windows.yml
  scripts/ansible/roles/windows/openenclave/vars/windows.yml
Labels: ansible

#1916 Add Cancel button to VS extension screen to pick an ARM board
  new_platforms/vsextension/ProjectWizard/BoardPickerPage.Designer.cs
  new_platforms/vsextension/ProjectWizard/WizardImplementation.cs
Labels: trustzone

#1868 Add use of feature flags to our contributing guidelines
  docs/Contributing.md
Labels: documentation

#1926 Unblock CI by disabling the crypto test on Windows temporarily.
  tests/CMakeLists.txt
Labels: ci/cd

#1408 Remove explicit USE_DEBUG_MALLOC disable
  .jenkins/Jenkinsfile
Labels: build, ci/cd, testing

#1939 Re-enable the crypto tests on Windows
  tests/CMakeLists.txt
Labels: ci/cd, testing

#1882 Add doc describing how to build OE in a Docker container.
  docs/GettingStartedDocs/Contributors/BuildingInADockerContainer.md
Labels: documentation

#1970 [CI/CD] Remove Ubuntu 16.04 simulation stages
  .jenkins/Jenkinsfile
Labels: ci/cd

#1968 Incorrect variable initialization in _do_eenter
  host/sgx/calls.c
Labels: bug, core

#1973 Update using_oe_sdk.md
  docs/GettingStartedDocs/using_oe_sdk.md
Labels: documentation

#1982 Fix dependencies for host and syscall EDL
  host/CMakeLists.txt
  syscall/CMakeLists.txt
Labels: build

#1976 Retry InitializeEnclave on Windows on SGX EINIT SGX_UNMASKED_EVENT error
  host/sgx/sgxload.c
  include/openenclave/internal/sgxtypes.h
Labels: bug, core, windows

#1945 Jenkins CI to test OE Windows with DCAP libraries
  .jenkins/Jenkinsfile
Labels: ci/cd

#1994 User documentation: Using the I/O Subsystem
  docs/UsingTheIOSubsystem.md
Labels: documentation

#1978 Add ninja install and usage to getting started docs
  docs/GettingStartedDocs/Contributors/InstallInfo.md
  docs/GettingStartedDocs/Contributors/SGX1FLCGettingStarted.md
  docs/GettingStartedDocs/install_oe_sdk-Ubuntu_16.04.md
  docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md
  docs/Releasing.md
Labels: documentation

#2002 Updated oesgx README.md to reflect current output
  tools/oesgx/README.md
Labels: devtools, documentation

#2014 Use GCC (GNU) atomic builtins for acquire-release
  include/openenclave/internal/utils.h
Labels: core

#2013 Add VC 2012 runtime install
  scripts/install-windows-prereqs.ps1
Labels: ci/cd

#2016 Include packages required for AArch64 testing.
  scripts/ansible/roles/linux/openenclave/vars/ubuntu.yml
Labels: ci/cd, trustzone
