Repository openenclave/openenclave, pull requests merged in 2019-01, with the labels that each got.

#1273 Fixed broken Jenkins file - Added back -d switch to disable simulator mode for CI tests on hardware
  .jenkins/Jenkinsfile
Labels: ci/cd, testing

#1284 Do not install pre-commit hook on Windows
  CMakeLists.txt
Labels: windows

#1297 Minor fixes for testing OE on Windows
  docs/GettingStartedDocs/GettingStarted.Windows.md
  tests/aesm/CMakeLists.txt
  tests/safemath/CMakeLists.txt
Labels: documentation, testing, windows

#1288 Added ntohl and ntohs object files to to the static C library.
  libc/CMakeLists.txt
Labels: bug

#1316 Removed requirement to source /etc/environment from ansible install prereqs
  scripts/ansible/tasks/ansible-install-prereqs.yml
Labels: ci/cd

#1315 Enable AESM enclave tracing
  enclave/core/sgx/tracee.c
Labels: engineering

#1378 Move sgx specific properties from properties.h to sgx/sgxproperties.h
  include/openenclave/bits/properties.h
  include/openenclave/bits/sgx/sgxproperties.h
  include/openenclave/internal/properties.h
  include/openenclave/internal/sgx/sgxproperties.h
Labels: core, trustzone

#1391 Disabled remote attestation tests temporarily.
  samples/remote_attestation/Makefile
  tests/report/CMakeLists.txt
Labels: ci/cd

#1380 Always export compile commands
  CMakeLists.txt
Labels: blocked, build

#1388 Fix comparison error
  tests/memory/enc/basic.c
Labels: blocked, ubuntu-18.04

#1389 Fix docker privileged flag
  .jenkins/Jenkinsfile
Labels: blocked

#1392 Fix edger8r target to be an imported executable
  cmake/oeedl_file.cmake
  tools/oeedger8r/CMakeLists.txt
Labels: build

#1393 Fix some typos in Emitter
  tools/oeedger8r/Emitter.ml
Labels: devtools

#1396 Revert "Disabled remote attestation tests temporarily."
  samples/remote_attestation/Makefile
  tests/report/CMakeLists.txt
Labels: blocked, ci/cd

#1401 Add default enclave_type flag for oe_create_enclave
  CHANGELOG.md
  host/sgx/create.c
  include/openenclave/bits/types.h
  samples/helloworld/README.md
  samples/helloworld/host/host.c
  tests/create-errors/host/host.c
Labels: core, trustzone
