Repository openenclave/openenclave, pull requests merged in 2019-05, with the labels that each got.

#1746 Remove pinned ansible packages.
  scripts/ansible/roles/linux/openenclave/vars/bionic.yml
  scripts/ansible/roles/linux/openenclave/vars/xenial.yml
Labels: bug

#1760 [Ansible] Remove version pinning for Docker package
  scripts/ansible/roles/linux/docker/vars/bionic.yml
  scripts/ansible/roles/linux/docker/vars/xenial.yml
Labels: ansible, ci/cd

#1763 Refactor the edger8r
  tools/oeedger8r/Emitter.ml
Labels: devtools

#1768 [cmake] Check if targets openenclave::oeedger8r and openenclave::oegdb are already defined
  cmake/openenclave-config.cmake.in
Labels: bug, build

#1769 [host/cmake] _FORTIFY_SOURCE should not be used on debug builds
  host/CMakeLists.txt
Labels: build

#1776 [CI/CD] Use bash with profile loaded for shell steps
  src/jenkins/common/Openenclave.groovy
Labels: ci/cd

#1774 Add `propagate_errno` oedger8r test
  tests/oeedger8r/edl/all.edl
  tests/oeedger8r/edl/errno.edl
  tests/oeedger8r/enc/CMakeLists.txt
  tests/oeedger8r/enc/testerrno.cpp
  tests/oeedger8r/host/CMakeLists.txt
  tests/oeedger8r/host/main.cpp
  tests/oeedger8r/host/testerrno.cpp
Labels: devtools

#1787 [Ansible] Apt repo refactor
  scripts/ansible/roles/linux/az-dcap-client/tasks/stable-install.yml
  scripts/ansible/roles/linux/common/tasks/apt-repo-intel.yml
  scripts/ansible/roles/linux/common/tasks/apt-repo-llvm.yml
  scripts/ansible/roles/linux/common/tasks/apt-repo.yml
  scripts/ansible/roles/linux/intel/tasks/sgx-packages.yml
  scripts/ansible/roles/linux/openenclave/tasks/environment-setup.yml
  scripts/ansible/roles/linux/openenclave/tasks/stable-install.yml
Labels: ansible, ci/cd

#1778 Added ocamlformat install to Ansible environment preparation
  scripts/ansible/inventory/group_vars/linux-agents
  scripts/ansible/roles/linux/openenclave/tasks/environment-setup.yml
  scripts/ansible/roles/linux/openenclave/tasks/opam-setup.yml
  scripts/ansible/roles/linux/openenclave/vars/bionic.yml
  scripts/ansible/roles/linux/openenclave/vars/ubuntu.yml
  scripts/ansible/roles/linux/openenclave/vars/xenial.yml
  scripts/ansible/roles/linux/validation/tasks/slave-validation.yml
  scripts/ansible/roles/linux/validation/vars/bionic.yml
  scripts/ansible/roles/linux/validation/vars/xenial.yml
Labels: ci/cd

#1790 [Ansible] Update Windows psw_archive_url and dcap_archive_url
  scripts/ansible/roles/windows/az-dcap-client/tasks/environment-setup.yml
  scripts/ansible/roles/windows/az-dcap-client/vars/windows.yml
Labels: ansible, ci/cd

#1805 Copy TA Dev Kits into predictable locations
  new_platforms/CMakeLists.txt
  new_platforms/scripts/05_prepare_nuget.sh
Labels: trustzone

#1796 Fix VS extension compiler options when user picks a custom ARM board
  new_platforms/vsextension/ProjectTemplates/oeenclave/sub.mk
  new_platforms/vsextension/ProjectWizard/BoardPickerPage.cs
  new_platforms/vsextension/ProjectWizard/ImportEnclaveCommand.cs
  new_platforms/vsextension/ProjectWizard/WizardImplementation.cs
Labels: trustzone

#1806 Make VSExtension work for edge modules
  new_platforms/vsextension/ProjectWizard/ImportEnclaveCommand.cs
Labels: trustzone

#1807 Update VS extension to use latest nuget package
  new_platforms/vsextension/ItemTemplates/oehost/host.vstemplate
  new_platforms/vsextension/ProjectTemplates/oeenclave/MyEnclave.vcxproj
  new_platforms/vsextension/ProjectTemplates/oeenclave/enclave.vstemplate
  new_platforms/vsextension/ProjectTemplates/oeenclave/sub.mk
  new_platforms/vsextension/ProjectWizard/ImportEnclaveCommand.cs
  new_platforms/vsextension/ProjectWizard/VS Extension.csproj
  new_platforms/vsextension/ProjectWizard/WizardImplementation.cs
  new_platforms/vsextension/ProjectWizard/source.extension.vsixmanifest
Labels: trustzone

#1814 Addressing typos in Ansible az-dcap-client environment-setup.yml
  scripts/ansible/roles/windows/az-dcap-client/tasks/environment-setup.yml
Labels: ansible

#1817 [Ansible] Windows validation refactor
  scripts/ansible/inventory/group_vars/windows-agents
  scripts/ansible/jenkins-setup.yml
  scripts/ansible/oe-windows-acc-setup.yml
  scripts/ansible/roles/windows/az-dcap-client/vars/windows.yml
  scripts/ansible/roles/windows/jenkins/tasks/slave-setup.yml
  scripts/ansible/roles/windows/jenkins/tasks/validation.yml
  scripts/ansible/roles/windows/jenkins/vars/windows.yml
  scripts/ansible/roles/windows/openenclave/tasks/environment-setup.yml
  scripts/ansible/roles/windows/openenclave/tasks/validation.yml
  scripts/ansible/roles/windows/openenclave/vars/windows.yml
Labels: ansible, ci/cd

#1830 Windows validation for DCAP
  scripts/ansible/oe-windows-acc-setup.yml
  scripts/ansible/roles/windows/az-dcap-client/tasks/validation.yml
  scripts/ansible/roles/windows/az-dcap-client/vars/windows.yml
Labels: ansible, ci/cd

#1764 Output progress to output view too
  new_platforms/vscode-extension/README.md
  new_platforms/vscode-extension/SetUpDevice.md
  new_platforms/vscode-extension/marketplace-homepage.md
  new_platforms/vscode-extension/package.json
  new_platforms/vscode-extension/src/common/constants.ts
  new_platforms/vscode-extension/src/common/gitHelper.ts
  new_platforms/vscode-extension/src/common/requirementsChecker.ts
  new_platforms/vscode-extension/src/extension.ts
  new_platforms/vscode-extension/src/openenclave/openEnclaveManager.ts
Labels: trustzone

#1727 Added checks to CMake find_library for crypto and dl
  cmake/openenclave-config.cmake.in
  host/CMakeLists.txt
Labels: build
