Repository openenclave/openenclave, pull requests merged in 2019-04, with the labels that each got.

#1651 Added 'apt update' command to install_oe_sdk-Ubuntu* docs.
  docs/GettingStartedDocs/install_oe_sdk-Ubuntu_16.04.md
  docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md
Labels: documentation

#1622 Update libc & libcxx support documents
  docs/LibcSupport.md
  docs/LibcxxSupport.md
Labels: core, documentation

#1647 Added/changed simulation mode documentation.
  docs/GettingStartedDocs/Contributors/SimulatorGettingStarted.md
  docs/GettingStartedDocs/install_oe_sdk-Simulation.md
Labels: documentation

#1653 Minor fixes to CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#1662 Fix samples test script
  samples/test-samples.cmake
Labels: build

#1658 Disable unattendend upgrades for packer generated VHDs
  .jenkins/provision/templates/packer/packer.json
Labels: ci/cd

#1667 Added oesign README.md.
  tools/oesign/README.md
  tools/oesign/main.c
Labels: documentation

#1670 Removed references to openssl from mbedtls README
  3rdparty/README.md
Labels: documentation

#1657 [CI] Discard old Bors Jenkins builds
  .jenkins/Jenkinsfile
Labels: ci/cd

#1674 Update Intel FLC driver dependency to v1.1
  docs/GettingStartedDocs/install_oe_sdk-Ubuntu_16.04.md
  docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md
  scripts/ansible/roles/linux/intel/vars/bionic.yml
  scripts/ansible/roles/linux/intel/vars/xenial.yml
Labels: ansible, ci/cd, documentation

#1675 Move `apt update` step before first `apt install`
  docs/GettingStartedDocs/install_oe_sdk-Ubuntu_16.04.md
  docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md
Labels: documentation

#1635 Added documentation on newly added CMake support for samples
  samples/README.md
  samples/data-sealing/README.md
  samples/file-encryptor/README.md
  samples/helloworld/README.md
  samples/local_attestation/README.md
  samples/remote_attestation/README.md
Labels: documentation

#1680 Add missing APT packages to be installed.
  scripts/ansible/roles/linux/intel/tasks/sgx-packages.yml
  scripts/ansible/roles/linux/intel/vars/bionic.yml
  scripts/ansible/roles/linux/intel/vars/xenial.yml
Labels: ansible

#1676 Fix language support assumptions in the CMake package
  cmake/openenclave-config.cmake.in
Labels: build

#1689 [Docs] Update outdated items from Edger8rGettingStarted.md
  docs/GettingStartedDocs/Edger8rGettingStarted.md
Labels: documentation

#1685 Remove clean/checkout commands from Openenclave.groovy common library
  .jenkins/Jenkinsfile
  .jenkins/Nightly_packages_testing.Jenkinsfile
  .jenkins/Packaging.Jenkinsfile
  .jenkins/libcxx_tests.Jenkinsfile
  src/jenkins/common/Openenclave.groovy
Labels: ci/cd

#1693 Added VHD_URL parameter for deployment templates.
  .jenkins/Nightly_packages_testing.Jenkinsfile
  .jenkins/libcxx_tests.Jenkinsfile
  .jenkins/provision/deploy-agent.sh
  .jenkins/provision/templates/oe-engine/ubuntu-bionic.json
  .jenkins/provision/templates/oe-engine/ubuntu-xenial.json
Labels: ci/cd

#1695 Update Jenkinsfile to use registry images
  .jenkins/Jenkinsfile
  src/jenkins/common/Openenclave.groovy
Labels: ci/cd

#1696 Fix emitted whitespace errors
  tools/oeedger8r/Emitter.ml
Labels: devtools

#1697 Limit testcase name to 120 chars.
  cmake/get_testcase_name.cmake
Labels: testing

#1694 Create Jenkinsfile for building docker images
  .jenkins/Dockerfile.full
  .jenkins/Dockerfile.minimal
  .jenkins/build_docker_images.Jenkinsfile
Labels: ci/cd

#1591 Avoid hard-coded paths in oe-gdb script.
  debugger/CMakeLists.txt
  debugger/oe-gdb
Labels: devtools

#1699 [CI/CD] Fix nightly packages testing
  .jenkins/Nightly_packages_testing.Jenkinsfile
Labels: ci/cd

#1607 Build OE libraries with more secure flags
  CHANGELOG.md
  common/oe_host_string.h
  enclave/core/CMakeLists.txt
  host/CMakeLists.txt
  pkgconfig/CMakeLists.txt
Labels: build, security

#1709 Update SGX driver link in SDK getting started docs
  docs/GettingStartedDocs/install_oe_sdk-Ubuntu_16.04.md
  docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md
Labels: documentation

#1710 Update SGX driver link in SDK getting started docs
  docs/GettingStartedDocs/install_oe_sdk-Ubuntu_16.04.md
  docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md
Labels: documentation

#1713 [CI/CD] Fix libcxx Jenkins job regression
  .jenkins/Nightly_packages_testing.Jenkinsfile
  .jenkins/build_vhd.Jenkinsfile
  .jenkins/libcxx_tests.Jenkinsfile
  src/jenkins/common/Openenclave.groovy
Labels: ci/cd

#1719 [CI/CD] Fix CI shared lib race condition
  src/jenkins/common/Openenclave.groovy
Labels: ci/cd

#1568 [samples] Remove unused enclave configuration files from samples
  samples/local_attestation/common/enc.conf
  samples/remote_attestation/common/enc.conf
Labels: samples

#1720 Fix error message in the data sealing sample
  samples/data-sealing/common/keys.cpp
Labels: bug

#1576 [samples] Remove unused target from local/remote attestation Makefiles
  samples/local_attestation/Makefile
  samples/remote_attestation/Makefile
Labels: build, samples

#1733 Remove `:PATH` from CMake variables
  3rdparty/libcxx/libcxx/benchmarks/CMakeLists.txt
  3rdparty/libcxx/libcxx/docs/BuildingLibcxx.rst
  3rdparty/libcxx/libcxx/utils/google-benchmark/cmake/HandleGTest.cmake
  cmake/package_settings.cmake
  docs/GettingStartedDocs/Contributors/InstallInfo.md
  docs/GettingStartedDocs/Contributors/building_oe_sdk.md
  scripts/test-build-config
Labels: documentation
