Repository openenclave/openenclave, pull requests merged in 2019-08, with the labels that each got.

#2071 Remove OE crypto generate_key_pair methods.
  enclave/crypto/ec.c
  enclave/crypto/rsa.c
  host/crypto/openssl/ec.c
  host/crypto/openssl/rsa.c
  include/openenclave/internal/crypto/ec.h
  include/openenclave/internal/rsa.h
  tests/crypto/ec_tests.c
  tests/crypto/rsa_tests.c
Labels: engineering, testing

#2083 Add build status badge
  README.md
Labels: documentation

#2084 Various readme updates
  README.md
Labels: documentation

#2085 Add design documents folder and template
  docs/Contributing.md
  docs/DesignDocs/README.md
Labels: documentation

#2086 Fix some formatting
  docs/GettingStartedDocs/install_oe_sdk-Ubuntu_16.04.md
  docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md
Labels: documentation

#2087 Update Windows prereqs to DCAP 1.2
  docs/GettingStartedDocs/GettingStarted.Windows.md
  scripts/install-windows-prereqs.ps1
Labels: build, documentation, windows

#2093 Add security policy and clean up license detection
  SECURITY.md
  scripts/.check-license.ignore
  scripts/check-license
Labels: documentation

#2110 Cleaned up error codes based off feedback in PR #2077.
  common/result.c
  common/sgx/qeidentity.c
  common/sgx/report.c
  enclave/sgx/report.c
  include/openenclave/bits/result.h
  tests/report/common/tests.cpp
Labels: engineering

#2111 Update docs to include link to windows installation
  README.md
  docs/GettingStartedDocs/Contributors/building_oe_sdk.md
  docs/GettingStartedDocs/GettingStarted.Windows.md
Labels: documentation

#2088 Community Maintenance Committee
  docs/GovernanceModel.md
  docs/Maintainers.md
Labels: documentation

#2120 Revisit OE SDK package settings
  cmake/cpack_settings.cmake
Labels: build

#2123 Remove root_index.txt and intermediate_index.txt from crypto tests on rebuild
  tests/crypto/data/make-test-certs
  tests/crypto_crls_cert_chains/data/make-test-certs
Labels: testing

#2133 Fix typo
  docs/DesignDocs/README.md
Labels: documentation

#2135 Add Bors enabled badge
  README.md
Labels: documentation
