Repository openenclave/openenclave, pull requests merged in 2020-03, with the labels that each got.

#2163 Add proposed API guidelines
  docs/ApiGuidelines.md
  docs/Contributing.md
Labels: process

#2592 OE SGX: Debugger Contract: SDK performs Ocall Stack Stitching
  CHANGELOG.md
  debugger/pythonExtension/gdb_sgx_plugin.py
  enclave/core/sgx/asmdefs.h
  enclave/core/sgx/calls.c
  enclave/core/sgx/enter.S
  enclave/core/sgx/exit.S
  enclave/core/sgx/hostcalls.c
  host/CMakeLists.txt
  host/sgx/asmdefs.h
  host/sgx/calls.c
  host/sgx/enter.c
  host/sgx/linux/hoststackbridge.c
  include/openenclave/internal/sgx/ecall_context.h
  tests/debugger/oegdb/commands.gdb
  tests/debugger/oegdb/enc/contract.c
  tests/debugger/oegdb/enc/enc.c
  tests/debugger/oegdb/host/host.c
  tests/debugger/oegdb/oe_gdb_test.edl
Labels: SGX, core, devtools, linux

#2600 Simulation Mode in Windows
  CHANGELOG.md
  CMakeLists.txt
  host/sgx/asmdefs.h
  host/sgx/calls.c
  host/sgx/create.c
  host/sgx/enclave.c
  host/sgx/enclave.h
  host/sgx/enter.c
  host/sgx/exception.c
  host/sgx/registers.c
  host/sgx/windows/aep.asm
  host/sgx/windows/exception.c
  host/sgx/windows/exception.h
  include/openenclave/internal/registers.h
  tests/CMakeLists.txt
Labels: SGX, SimulationMode, core, devtools, windows

#2613 Add mbedTLS 2.16 tests to OE mbed tests
  tests/mbed/README.md
  tests/mbed/tests.supported
  tests/mbed/tests.unsupported
Labels: testing

#2653 Fix backtrace test under gcc 8
  tests/backtrace/enc/enc.cpp
Labels: testing

#2651 Refactor compiler detection logic into separate config.mk
  samples/CMakeLists.txt
  samples/attested_tls/client/enc/Makefile
  samples/attested_tls/client/host/Makefile
  samples/attested_tls/non_enc_client/Makefile
  samples/attested_tls/server/enc/Makefile
  samples/attested_tls/server/host/Makefile
  samples/config.mk
  samples/data-sealing/enclave_a_v1/Makefile
  samples/data-sealing/enclave_a_v2/Makefile
  samples/data-sealing/enclave_b/Makefile
  samples/data-sealing/host/Makefile
  samples/file-encryptor/enclave/Makefile
  samples/file-encryptor/host/Makefile
  samples/helloworld/README.md
  samples/helloworld/enclave/Makefile
  samples/helloworld/host/Makefile
  samples/local_attestation/enclave_a/Makefile
  samples/local_attestation/enclave_b/Makefile
  samples/local_attestation/host/Makefile
  samples/remote_attestation/enclave_a/Makefile
  samples/remote_attestation/enclave_b/Makefile
  samples/remote_attestation/host/Makefile
  samples/switchless/enclave/Makefile
  samples/switchless/host/Makefile
Labels: SGX, samples

#2667 Update mbedTLS to v2.16.5
  3rdparty/mbedtls/mbedtls/ChangeLog
  3rdparty/mbedtls/mbedtls/doxygen/input/doc_mainpage.h
  3rdparty/mbedtls/mbedtls/doxygen/mbedtls.doxyfile
  3rdparty/mbedtls/mbedtls/include/mbedtls/version.h
  3rdparty/mbedtls/mbedtls/library/CMakeLists.txt
  3rdparty/mbedtls/mbedtls/library/bignum.c
  3rdparty/mbedtls/mbedtls/library/cipher.c
  3rdparty/mbedtls/mbedtls/library/ecdsa.c
  3rdparty/mbedtls/mbedtls/library/pkparse.c
  3rdparty/mbedtls/mbedtls/library/rsa.c
  3rdparty/mbedtls/mbedtls/library/x509write_csr.c
  3rdparty/mbedtls/mbedtls/tests/scripts/all.sh
  3rdparty/mbedtls/mbedtls/tests/ssl-opt.sh
  3rdparty/mbedtls/mbedtls/tests/suites/test_suite_ecdsa.function
  3rdparty/mbedtls/mbedtls/tests/suites/test_suite_mpi.data
  3rdparty/mbedtls/mbedtls/tests/suites/test_suite_mpi.function
  3rdparty/mbedtls/mbedtls/tests/suites/test_suite_pk.function
  3rdparty/mbedtls/mbedtls/tests/suites/test_suite_pkparse.data
  3rdparty/mbedtls/mbedtls/tests/suites/test_suite_pkparse.function
  3rdparty/mbedtls/mbedtls/tests/suites/test_suite_version.data
  3rdparty/mbedtls/update.make
  CHANGELOG.md
Labels: security

#2663 add acc contributor template with no sgx package install
  scripts/ansible/oe-contributors-acc-setup-no-psw.yml
Labels: ansible

#2545 Design proposal for digest signing support in oesign
  docs/DesignDocs/images/oesign_dev_signing.svg
  docs/DesignDocs/images/oesign_digest_signing.svg
  docs/DesignDocs/oesign_digest_signing_support.md
Labels: design, devtools

#2677 Allocate and associate ocall buffers with TCS.
  host/sgx/create.c
  host/sgx/enclave.h
  host/sgx/enter.c
  tests/ecall_ocall/ecall_ocall.edl
  tests/ecall_ocall/enc/enc.cpp
  tests/ecall_ocall/host/host.cpp
Labels: SGX, bug, core

#2699 Update the checks of GCC version to bypass the failing libcxx test case
  tests/libcxx/CMakeLists.txt
  tests/libcxx/enc/CMakeLists.txt
Labels: testing

#2712 Add missing dependencies to `oehostmr`
  host/measure/CMakeLists.txt
Labels: build

#2621 Design doc - Attestation plugins query and selection
  docs/DesignDocs/CustomAttestation_V3.md
Labels: process

#2723 Prevent regeneration of asym_keys.h
  host/CMakeLists.txt
Labels: bug, build

#2755 Remove loadpe.c from the SGX loader
  host/CMakeLists.txt
  host/measure/CMakeLists.txt
  host/sgx/load.c
  host/sgx/loadpe.c
  include/openenclave/internal/load.h
Labels: SGX, core

#2678 Attestation: OE SDK Integration with Intel® SGX SDK quote-ex Library for Evidence Generation in New Formats
  docs/DesignDocs/SGX_QuoteEx_Integration.md
Labels: SGX, attestation, design

#2732 add test cases about child process
  tests/CMakeLists.txt
  tests/child_process/CMakeLists.txt
  tests/child_process/README.md
  tests/child_process/child_process.edl
  tests/child_process/enc/CMakeLists.txt
  tests/child_process/enc/enc.cpp
  tests/child_process/host/CMakeLists.txt
  tests/child_process/host/host.cpp
Labels: testing

#2739 Update Azure.DCAP.Windows v0.0.3 to Microsoft.Azure.DCAP v1.3.0
  cmake/add_dcap_client_target.cmake
  docs/GettingStartedDocs/Contributors/WindowsManualSGX1FLCDCAPPrereqs.md
  scripts/ansible/oe-windows-acc-setup.yml
  scripts/install-windows-prereqs.ps1
  tests/attestation_plugin/host/CMakeLists.txt
Labels: build, ci/cd

#2731 Append sdk testing atexit
  tests/CMakeLists.txt
  tests/atexit/CMakeLists.txt
  tests/atexit/README.md
  tests/atexit/atexit.edl
  tests/atexit/enc/CMakeLists.txt
  tests/atexit/enc/enc.cpp
  tests/atexit/host/CMakeLists.txt
  tests/atexit/host/host.cpp
Labels: testing

#2735 Update the libc++ support
  3rdparty/libcxx/CMakeLists.txt
  docs/LibcxxSupport.md
  tests/libcxx/CMakeLists.txt
  tests/libcxx/enc/CMakeLists.txt
  tests/libcxx/tests.broken
  tests/libcxx/tests.supported
  tests/libcxx/tests.supported.cxx17
  tests/libcxx/tests.unsupported
Labels: testing
