Repository openenclave/openenclave, pull requests merged in 2020-04, with the labels that each got.

#2636 SGX: Switchless ECALLs implementation
  CHANGELOG.md
  common/sgx/edl/switchless.edl
  enclave/core/sgx/calls.c
  enclave/core/sgx/handle_ecall.h
  enclave/core/sgx/switchlesscalls.c
  host/sgx/calls.c
  host/sgx/create.c
  host/sgx/linux/switchless.c
  host/sgx/switchless.c
  host/sgx/windows/switchless.c
  include/openenclave/internal/atomic.h
  include/openenclave/internal/switchless.h
  samples/switchless/README.md
  samples/switchless/enclave/enc.c
  samples/switchless/enclave/switchless.conf
  samples/switchless/host/host.c
  samples/switchless/switchless.edl
  tests/backtrace/host/host.cpp
  tests/oeedger8r/behavior/CMakeLists.txt
  tests/oeedger8r/behavior/switchless_trusted.edl
  tests/switchless/CMakeLists.txt
  tests/switchless/enc/enc.c
  tests/switchless/host/host.c
  tests/switchless/switchless.edl
  tools/oeedger8r/src/Emitter.ml
Labels: SGX, core

#2722 Design document for Pluggable Allocators
  docs/DesignDocs/PluggableAllocators.md
Labels: core, design, functionality

#2836 Disable EC fixed key test to unblock WS2019 testing
  tests/crypto/ec_tests.c
Labels: testing

#2830 Add Windows support for getnameinfo and getaddrinfo
  common/oe_host_socket.h
  host/linux/syscall.c
  host/windows/syscall.c
  tests/syscall/CMakeLists.txt
  tests/syscall/resolver/enc/enc.c
  tests/syscall/resolver/host/host.c
  tests/syscall/resolver/resolver_test.edl
  tests/syscall/resolver/utils.h
Labels: windows

#2820 Fix scripts/install-windows-prereqs.ps1 script
  scripts/install-windows-prereqs.ps1
Labels: ci/cd, engineering, windows

#2733 add test cases about child thread
  tests/CMakeLists.txt
  tests/child_thread/CMakeLists.txt
  tests/child_thread/README.md
  tests/child_thread/child_thread.edl
  tests/child_thread/enc/CMakeLists.txt
  tests/child_thread/enc/enc.cpp
  tests/child_thread/host/CMakeLists.txt
  tests/child_thread/host/host.cpp
Labels: testing

#2744 Add CGC mailing list to documentation
  docs/CodeOfConduct.md
  docs/Committers.md
Labels: documentation, process

#2904 Update install-windows-prereqs.ps1
  scripts/install-windows-prereqs.ps1
Labels: ci/cd

#2905 Add to getting started doc possibility of SGX driver being preinstalled
  docs/GettingStartedDocs/install_oe_sdk-Ubuntu_16.04.md
  docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md
Labels: SGX, documentation

#2931 Intel PSW update
  scripts/ansible/oe-windows-acc-setup.yml
  scripts/ansible/roles/linux/intel/vars/ubuntu/main.yml
Labels: ci/cd

#2778 Restructure and update community governance docs
  README.md
  docs/ApiGuidelines.md
  docs/CODE_OF_CONDUCT.md
  docs/Committers.md
  docs/Community/CodeOfConduct.md
  docs/Community/Committers.md
  docs/Community/Communication.md
  docs/Community/Contributing.md
  docs/Community/DevelopmentGuide.md
  docs/Community/Governance.md
  docs/Community/README.md
  docs/Community/ReleaseProcess.md
  docs/Community/Releasing.md
  docs/Community/conduct/ConflictPolicy.md
  docs/Community/conduct/IncidentResponseGuidelines.md
  docs/Community/conduct/README.md
  docs/Community/governance/OWNERS
  docs/Community/governance/README.md
  docs/Community/governance/charter.md
  docs/Community/governance/sig-charter-template.md
  docs/Community/sig-api/OWNERS
  docs/Community/sig-api/README.md
  docs/Community/sig-architecture/OWNERS
  docs/Community/sig-architecture/README.md
  docs/Community/sig-attestation/OWNERS
  docs/Community/sig-attestation/README.md
  docs/Community/sig-optee/OWNERS
  docs/Community/sig-release/OWNERS
  docs/Community/sig-release/charter.md
  docs/Community/sig-sgx/OWNERS
  docs/Community/sig-testing/OWNERS
  docs/Community/sig-testing/README.md
  docs/Community/sig-tools/OWNERS
  docs/Community/sig-website/OWNERS
  docs/Community/wg-triage/README.md
  docs/GettingStartedDocs/README.md
  docs/Governance.md
  scripts/.check-license.ignore
Labels: needs review, process, triaged

#2942 Update docs of installation OE on windows
  docs/GettingStartedDocs/Contributors/WindowsManualSGX1FLCDCAPPrereqs.md
  docs/GettingStartedDocs/install_oe_sdk-Windows.md
Labels: documentation

#2922 Fix the print test on cross-compilation configurations
  tests/print/CMakeLists.txt
Labels: testing, windows

#2939 one more child process case
  tests/child_process/CMakeLists.txt
  tests/child_process/host/host.cpp
Labels: testing

#2936 Fix format-code string -> array bugs
  scripts/format-code
Labels: bug, devtools

#2911 Update manual instructions for Windows Server 2019
  docs/GettingStartedDocs/Contributors/WindowsManualSGX1FLCDCAPPrereqs.md
  docs/GettingStartedDocs/Contributors/WindowsManualSGX1Prereqs.md
Labels: documentation, windows
