Repository openenclave/openenclave, pull requests merged in 2020-01, with the labels that each got.

#2411 oe_enter_sim manages GS and FS registers
  host/sgx/calls.c
  host/sgx/enclave.h
  host/sgx/enter.c
Labels: SGX

#2395 Enable test/ecall_ocall on windows
  tests/CMakeLists.txt
  tests/ecall_ocall/host/host.cpp
Labels: testing, windows

#2307 The stack guard for OE SDK on SGX is turned on.
  CHANGELOG.md
  debugger/pythonExtension/gdb_sgx_plugin.py
  enclave/core/CMakeLists.txt
  enclave/core/sgx/calls.c
  enclave/core/sgx/enter.S
  enclave/core/sgx/exit.S
  enclave/core/sgx/linux/threadlocal.c
  enclave/core/sgx/td.c
  enclave/core/sgx/td.h
  enclave/core/sgx/td_basic.c
  enclave/core/sgx/thread.c
  host/README.md
  host/sgx/create.c
  include/openenclave/internal/constants_x64.h
  include/openenclave/internal/sgxtypes.h
  tests/CMakeLists.txt
  tests/debugger/oegdb/enc/contract.c
  tests/stack_smashing_protector/CMakeLists.txt
  tests/stack_smashing_protector/enc/CMakeLists.txt
  tests/stack_smashing_protector/enc/enc.cpp
  tests/stack_smashing_protector/host/CMakeLists.txt
  tests/stack_smashing_protector/host/host.cpp
  tests/stack_smashing_protector/ssp.edl
  tests/stdcxx/CMakeLists.txt
  tests/stdcxx/host/host.cpp
Labels: SGX

#2415 Update OE SDK contact alias to oesdk@lists.confidentialcomputing.io
  THIRD_PARTY_NOTICES
  cmake/cpack_settings.cmake
Labels: documentation

#2389 Enable /W2 to treat W2 warnings as errors for Windows builds
  cmake/compiler_settings.cmake
  include/openenclave/edger8r/common.h
  tools/oeedger8r/src/Sources.ml
Labels: build, windows

#2303 Add malloc_usable_size
  docs/LibcSupport.md
  enclave/core/debugmalloc.c
  enclave/core/debugmalloc.h
  enclave/core/malloc.c
  include/openenclave/corelibc/bits/malloc.h
  include/openenclave/corelibc/stdlib.h
  tests/memory/enc/basic.c
  tests/memory/host/host.cpp
  tests/memory/memory.edl
Labels: core

#2435 Update PSW and DCAP Dependencies for Intel Release
  CHANGELOG.md
  docs/GettingStartedDocs/Contributors/BuildingInADockerContainer.md
  docs/GettingStartedDocs/Contributors/WindowsManualInstallPrereqs.md
  docs/GettingStartedDocs/Contributors/WindowsManualSGX1FLCDCAPPrereqs.md
  docs/GettingStartedDocs/Contributors/WindowsManualSGX1Prereqs.md
  docs/GettingStartedDocs/install_oe_sdk-Ubuntu_16.04.md
  docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md
  scripts/ansible/oe-windows-acc-setup.yml
  scripts/ansible/roles/linux/intel/vars/ubuntu.yml
  scripts/install-windows-prereqs.ps1
Labels: ansible, ci/cd, dependencies

#2420 Add documentation for libc initialization
  docs/DesignDocs/libc_initialization.md
Labels: do not merge, documentation

#2377 Attempt to handle syscalls without ocall first
  libc/syscalls.c
Labels: needs review

#2441 Add more guidelines for authoring commits to the contribution guidelines
  docs/Contributing.md
Labels: documentation

#2427 Support the deep copy of out-only parameters
  include/openenclave/edger8r/common.h
  tests/oeedger8r/edl/deepcopy.edl
  tests/oeedger8r/enc/testdeepcopy.cpp
  tests/oeedger8r/host/testdeepcopy.cpp
  tools/oeedger8r/src/Sources.ml
Labels: core

#2400 Enable test\libunwind on Windows
  tests/CMakeLists.txt
  tests/libunwind/CMakeLists.txt
  tests/libunwind/enc/CMakeLists.txt
  tests/libunwind/enc/enc.c
  tests/libunwind/host/host.cpp
Labels: testing, windows

#2434 Allow windows build to get the compiler information of pre-built test
  tests/libcxx/CMakeLists.txt
  tests/libcxx/enc/CMakeLists.txt
Labels: build, testing, windows
