Repository openenclave/openenclave, pull requests merged in 2020-11, with the labels that each got.

#3638 devex: Add collateral to build the cross-platform NuGet package
  .gitignore
  devex/cross-nuget/README.md
  devex/cross-nuget/extras/open-enclave-cross.nuspec
  devex/cross-nuget/linux/driver.sh
  devex/cross-nuget/linux/pack.sh
  devex/cross-nuget/linux/runner.sh
  devex/cross-nuget/linux/setup-containers.sh
  devex/cross-nuget/linux/setup-host.sh
  devex/cross-nuget/windows/build.ps1
  devex/cross-nuget/windows/pack.ps1
Labels: devex

#3609 Document OE Visual Studio extension release process
  devex/vsextension/README.md
  devex/vsextension/vsix-release-process.md
Labels: devtools

#3687 Jordan stepping down from CGC
  docs/Community/governance/README.md
Labels: process

#3709 Update SecurityAdvisoryHandling.md based on feedback
  docs/Community/SecurityAdvisoryHandling.md
Labels: documentation, process

#3499 Add proper EEID endorsements and move SGX endorsements there.
  common/sgx/eeid.c
  common/sgx/eeid_verifier.c
  common/sgx/verifier.c
  enclave/sgx/eeid_attester.c
  include/openenclave/bits/eeid.h
  include/openenclave/internal/eeid.h
  include/openenclave/internal/sgx/plugin.h
  tests/eeid_plugin/enc/enc.c
  tests/eeid_plugin/host/host.c
  tests/eeid_plugin/test_helpers.c
Labels: SGX, attestation

#3721 Cleanup ABI state preservation on enclave transitions
  enclave/core/sgx/asmdefs.c
  enclave/core/sgx/calls.c
  enclave/core/sgx/context.h
  enclave/core/sgx/context.inc
  enclave/core/sgx/enter.S
  enclave/core/sgx/exception.c
  enclave/core/sgx/td.h
  host/sgx/asmdefs.h
  host/sgx/create.c
  host/sgx/enter.c
  host/sgx/exception.h
  host/sgx/xstate.h
  include/openenclave/bits/defs.h
  include/openenclave/internal/constants_x64.h
  tests/abi/abi.edl
  tests/abi/abi_utils.h
  tests/abi/enc/enc.cpp
  tests/abi/host/CMakeLists.txt
  tests/abi/host/host.cpp
  tests/libc/enc/enc.c
  tests/libc/host/host.cpp
  tests/props/README.md
  tests/props/host/host.c
Labels: SGX, core

#3732 Verify oe report with null format id
  common/attest_plugin.c
  docs/DesignDocs/AttestationEvidenceFormatSupport.md
  docs/DesignDocs/Attestation_API_Proposal.md
  include/openenclave/attestation/verifier.h
  tests/attestation_plugin/plugin/tests.c
Labels: API, attestation

#3740 Replace references to legacy APIs
  samples/attested_tls/AttestedTLSREADME.md
Labels: attestation

#3747 Don't crash if oe_get_report is used in simulation mode
  enclave/core/sgx/report.c
  tests/report/host/host.cpp
Labels: attestation
