Repository openenclave/openenclave, pull requests merged in 2020-02, with the labels that each got.

#2399 Enable create-rapid for sgx on windows
  tests/CMakeLists.txt
  tests/create-rapid/enc/enc.cpp
  tests/create-rapid/host/host.cpp
Labels: SGX, testing, windows

#2403 Enable tests/libcxx on Windows
  tests/CMakeLists.txt
  tests/libcxx/enc/CMakeLists.txt
  tests/libcxx/enc/enc.cpp
  tests/libcxx/host/host.cpp
  tests/libcxx/tests.broken
  tests/libcxx/tests.supported
  tests/libcxx/tests.supported.default
Labels: linux, testing, windows

#2408 Add instructions for how to exclude files/directories from scan-build
  docs/GettingStartedDocs/Contributors/RunningStaticAnalysis.md
Labels: documentation, needs review

#2505 Ignore ~/.gdbinit when running oegdb tests
  tests/debugger/oegdb/CMakeLists.txt
Labels: testing

#2514 Update Readme to include Windows Package installation link
  README.md
Labels: documentation, windows

#2504 Improve documentation for SGXSupportLevel
  docs/GettingStartedDocs/SGXSupportLevel.md
Labels: documentation

#2553 Add test to make an OCall in the enclave Vectored Exception Handler
  tests/VectorException/VectorException.edl
  tests/VectorException/enc/enc.c
  tests/VectorException/host/host.c
Labels: core, testing

#2564 [CI/CD] Fix NSIS setup
  scripts/install-windows-prereqs.ps1
Labels: ci/cd

#2576 Add Jordan to CGC in Committers.md
  docs/Committers.md
Labels: documentation

#2495 Optimize switchless ocall scheduling
  host/sgx/switchless.c
  tests/switchless/enc/enc.c
  tests/switchless/host/host.c
  tests/switchless/switchless.edl
Labels: SGX, core

#2578 Cleanup simulation mode to use the GetThreadBinding function
  host/sgx/calls.c
Labels: SGX, core, linux

#2460 Fix SGX prereq installation instructions for Windows 10
  docs/GettingStartedDocs/Contributors/WindowsSGX1FLCGettingStarted.md
  docs/GettingStartedDocs/Contributors/WindowsSGX1GettingStarted.md
  scripts/install-windows-prereqs.ps1
Labels: SGX, documentation

#2608 libmbedcrypto.a is missing symbols.
  3rdparty/mbedtls/CMakeLists.txt
  CHANGELOG.md
Labels: bug
