Repository openenclave/openenclave, pull requests merged in 2021-08, with the labels that each got.

#4207 Never set errno to zero in malloc and related functions
  enclave/core/debugmalloc.c
  enclave/core/malloc.c
  tests/memory/enc/basic.c
Labels: API, bug

#4196 Support compiler-rt
  .gitignore
  3rdparty/CMakeLists.txt
  3rdparty/compiler-rt/CMakeLists.txt
  CHANGELOG.md
  libc/CMakeLists.txt
  tests/CMakeLists.txt
  tests/compiler_rt/CMakeLists.txt
  tests/compiler_rt/compiler_rt.edl
  tests/compiler_rt/enc/CMakeLists.txt
  tests/compiler_rt/enc/enc.c
  tests/compiler_rt/host/CMakeLists.txt
  tests/compiler_rt/host/host.c
Labels: libc

#4206 Reduce Linux image size
  .jenkins/infrastructure/docker/dockerfiles/linux/Dockerfile
  scripts/ansible/roles/linux/openenclave/tasks/ubuntu/lvi-setup.yml
Labels: ci/cd

#4224 Disable optimizations for testcase
  3rdparty/compiler-rt/CMakeLists.txt
  tests/compiler_rt/enc/CMakeLists.txt
Labels: testing

#4157 oeapkman: Package Manager and Toolbox for Enclaves on Linux
  CHANGELOG.md
  CMakeLists.txt
  cmake/openenclave-config.cmake.in
  cmake/sdk_cmake_targets_readme.md
  docs/GettingStartedDocs/OP-TEE/Debugging/QEMU.md
  samples/CMakeLists.txt
  samples/apkman/CMakeLists.txt
  samples/apkman/Makefile
  samples/apkman/README.md
  samples/apkman/enclave/CMakeLists.txt
  samples/apkman/enclave/Makefile
  samples/apkman/enclave/enc.c
  samples/apkman/enclave/main.c
  samples/apkman/enclave/sqlite.conf
  samples/apkman/enclave/stubs.c
  samples/apkman/host/CMakeLists.txt
  samples/apkman/host/Makefile
  samples/apkman/host/host.c
  samples/apkman/sqlite.edl
  samples/test-samples.cmake
  scripts/.check-license.ignore
  syscall/syscall.c
  tests/tools/CMakeLists.txt
  tests/tools/oeapkman/CMakeLists.txt
  tests/tools/oeapkman/sqlite/CMakeLists.txt
  tests/tools/oeapkman/sqlite/enc/CMakeLists.txt
  tests/tools/oeapkman/sqlite/enc/enc.c
  tests/tools/oeapkman/sqlite/enc/main.c
  tests/tools/oeapkman/sqlite/enc/stubs.c
  tests/tools/oeapkman/sqlite/host/CMakeLists.txt
  tests/tools/oeapkman/sqlite/host/host.c
  tests/tools/oeapkman/sqlite/test.edl
  tests/tools/oeapkman/zlib/CMakeLists.txt
  tests/tools/oeapkman/zlib/enc/CMakeLists.txt
  tests/tools/oeapkman/zlib/enc/enc.c
  tests/tools/oeapkman/zlib/enc/zpipe.c
  tests/tools/oeapkman/zlib/host/CMakeLists.txt
  tests/tools/oeapkman/zlib/host/host.c
  tests/tools/oeapkman/zlib/test.edl
  tools/CMakeLists.txt
  tools/oeapkman/CMakeLists.txt
  tools/oeapkman/oeapkman
Labels: OP-TEE, devtools, SGX, linux, devex

#4229 Ensure that expected number of compiler-rt tests are run.
  tests/compiler_rt/enc/CMakeLists.txt
Labels: testing

#4170 mmap and munmap implementations
  include/openenclave/internal/safemath.h
  libc/CMakeLists.txt
  libc/mman.c
  libc/mman.h
  libc/syscalls.c
  tests/CMakeLists.txt
  tests/mman/CMakeLists.txt
  tests/mman/enc/CMakeLists.txt
  tests/mman/enc/enc.c
  tests/mman/host/CMakeLists.txt
  tests/mman/host/host.c
  tests/mman/mman.edl
Labels: API
