Repository openenclave/openenclave, pull requests merged in 2021-07, with the labels that each got.

#4158 Fix incorrect dependency
  tests/edl_opt_out/enc/CMakeLists.txt
Labels: bug, testing

#4160 More complex math functions from MUSL
  libc/CMakeLists.txt
Labels: API

#4161 conf functions from MUSL
  include/openenclave/internal/syscall/declarations.h
  libc/CMakeLists.txt
  libc/sysconf.c
  syscall/syscall.c
Labels: API

#4159 Add more MUSL time functions.
  libc/CMakeLists.txt
Labels: API

#4164 Add repository links for Azure DCAP Client
  docs/GettingStartedDocs/Contributors/NonAccMachineSGXLinuxGettingStarted.md
  docs/GettingStartedDocs/Contributors/WindowsSGX1FLCGettingStarted.md
Labels: documentation

#4187 Override Intel build status
  .jenkins/pipelines/Intel/Linux/Jenkinsfile
Labels: ci/cd

#4179 Add missing MUSL search, string, stdlib functions.
  enclave/core/debugmalloc.c
  enclave/core/malloc.c
  libc/CMakeLists.txt
  tests/libc/tests.cmake
  tests/memory/enc/basic.c
  tests/openssl/enc/CMakeLists.txt
  tests/report/enc/CMakeLists.txt
Labels: libc

#4190 Fix eeid_plugin test failure with USE_SNMALLOC=on
  tests/eeid_plugin/test_helpers.c
Labels: testing
