Repository openenclave/openenclave, pull requests merged in 2021-05, with the labels that each got.

#3947 Publish oecert and oecert_enc.signed to /opt/openenclave/bin
  .jenkins/pipelines/Azure/Linux/Jenkinsfile
  tests/tools/CMakeLists.txt
  tests/tools/oecert/README.md
  tools/CMakeLists.txt
  tools/oecert/CMakeLists.txt
  tools/oecert/README.md
  tools/oecert/enc/CMakeLists.txt
  tools/oecert/enc/enc.conf
  tools/oecert/enc/enc.cpp
  tools/oecert/gen_pubkey_header.sh
  tools/oecert/host/CMakeLists.txt
  tools/oecert/host/evidence.cpp
  tools/oecert/host/evidence.h
  tools/oecert/host/host.cpp
  tools/oecert/oecert.edl
Labels: devex

#3994 Add OpenSSL path to Windows
  docs/GettingStartedDocs/Contributors/WindowsManualInstallPrereqs.md
  docs/GettingStartedDocs/install_oe_sdk-Windows.md
  scripts/install-windows-prereqs.ps1
Labels: devex

#3914 Provide crypto choice from VS extension
  devex/vsextension/ProjectWizard/VCTargets/1033/openenclave-general.xml
  devex/vsextension/ProjectWizard/VCTargets/OpenEnclave.Cpp.Clang.targets
  devex/vsextension/msbuild/open-enclave-cross.targets
Labels: devex

#4010 Fix Windows image builds
  .jenkins/infrastructure/build_azure_managed_images.Jenkinsfile
  scripts/ansible/oe-windows-acc-setup.yml
Labels: ansible

#3948 Update Intel SGX DCAP and PSW
  scripts/ansible/oe-windows-acc-setup.yml
  scripts/ansible/roles/linux/intel/vars/redhat/ootpa.yml
  scripts/ansible/roles/linux/intel/vars/ubuntu/bionic.yml
  scripts/ansible/roles/linux/intel/vars/ubuntu/focal.yml
  scripts/install-windows-prereqs.ps1
Labels: SGX

#3875 Skip CI tests for specific folders
  .jenkins/Jenkinsfile
Labels: ci/cd

#4049 Implement PEEK_USER and POKE_USER
  debugger/ptraceLib/ptrace.c
Labels: SGX, devtools
