Repository openenclave/openenclave, pull requests merged in 2021-09, with the labels that each got.

#4245 Fix optee test
  tests/tools/oeapkman/CMakeLists.txt
Labels: testing, OP-TEE

#4252 getopt support
  libc/CMakeLists.txt
Labels: libc

#4221 Jenkins Shared Library, and tests for releases and release candidates
  .jenkins/library/vars/common.groovy
  .jenkins/library/vars/globalvars.groovy
  .jenkins/library/vars/helpers.groovy
  .jenkins/library/vars/tests.groovy
  .jenkins/pipelines/Agnostic/Linux/Jenkinsfile
  .jenkins/pipelines/Azure/Linux/Jenkinsfile
  .jenkins/pipelines/Azure/Windows/Jenkinsfile
  .jenkins/pipelines/OpenEnclave/releases/tests/Jenkinsfile
Labels: ci/cd
